name: Release Bunk
run-name: Release Bunk (via ${{ github.event_name }} on ${{ inputs.ref }})

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: ''
        description: Target branch or ref to run build against
  push:
    branches:
      - main
    paths:
      - .github/workflows/bunk-release.yml


jobs:

  build:
    name: Build packages
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-15
          - ubuntu-22.04
          - windows-2019
        include:
          - os: macos-14
            CMD_LIST_DIR: ls -lR
            ZIP_CUSTOM_PARAMS: --symlinks
          - os: ubuntu-20.04
            CMD_LIST_DIR: ls -lR
            ZIP_CUSTOM_PARAMS: --symlinks
          - os: windows-2019
            CMD_LIST_DIR: tree /f
            ZIP_CUSTOM_PARAMS: ""


    steps:
      - uses: actions/checkout@v4
        with:
          repository: jahan01/bunk-qt
          ref: ${{ inputs.ref }}
          ssh-key: ${{ secrets.BUNK_DEPLOY_KEY }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install unixodbc
        if: matrix.os == 'macos-14'
        run: |
          which python
          which pip
          brew install unixodbc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/build.txt

      - name: Install dependencies (windows)
        if: matrix.os == 'windows-2019'
        run: |
          pip install -r requirements/windows.txt

      - name: Build package
        run: python bundle.py

      - name: List dist
        run: ${{ matrix.CMD_LIST_DIR}} dist

      - name: Archive Build
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          directory: dist
          filename: Bunk-${{ matrix.os }}.zip
          custom: ${{ matrix.ZIP_CUSTOM_PARAMS }}

      - uses: actions/upload-artifact@v4
        with:
          name: Bunk-${{ matrix.os }}
          path: ./dist/Bunk-${{ matrix.os }}.zip
